import { Prisma } from "@prisma/client";

// auto-generated by shim script

declare module "@prisma/client" {
  export enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    ANAH_AGENT = "ANAH_AGENT",
    CDC_AGENT = "CDC_AGENT",
    LANDLORD = "LANDLORD",
    LANDLORD_PRO = "LANDLORD_PRO",
    AGENCY = "AGENCY",
    TENANT = "TENANT",
    NON_CERTIFIED_AGENT = "NON_CERTIFIED_AGENT",
    CHAMPION = "CHAMPION",
  }

  export enum CDCDepositStatus {
    AWAITING_PAYMENT = "AWAITING_PAYMENT",
    PENDING = "PENDING",
    CONSIGNED = "CONSIGNED",
    RETURN_REQUESTED = "RETURN_REQUESTED",
    RETURNED = "RETURNED",
    FORFEITED = "FORFEITED",
  }

  export enum CDCDepositInitiator {
    OWNER = "OWNER",
    AGENCY = "AGENCY",
    ADMIN = "ADMIN",
  }

  export enum LeaseStatus {
    DRAFT = "DRAFT",
    PENDING_SIGNATURE = "PENDING_SIGNATURE",
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
    PENDING_DEPOSIT = "PENDING_DEPOSIT",
    ACTIVE = "ACTIVE",
    ACTIVE_DECLARATIF = "ACTIVE_DECLARATIF",
    LOYER_IMPAYE = "LOYER_IMPAYE",
    MISE_EN_DEMEURE = "MISE_EN_DEMEURE",
    CLEMENCE_EN_COURS = "CLEMENCE_EN_COURS",
    REPRISE_PROCEDURE = "REPRISE_PROCEDURE",
    DEMANDE_RESILIATION = "DEMANDE_RESILIATION",
    TERMINATED = "TERMINATED",
    CANCELLED = "CANCELLED",
    ARCHIVED = "ARCHIVED",
  }

  export enum TypeBail {
    ECRIT = "ECRIT",
    DECLARATIF_BDQ = "DECLARATIF_BDQ",
    DECLARATIF_EN_COURS_FORMALISATION = "DECLARATIF_EN_COURS_FORMALISATION",
  }

  export enum PlanTier {
    LOCATAIRE = "LOCATAIRE",
    ESSENTIEL = "ESSENTIEL",
    PRO = "PRO",
    PREMIUM = "PREMIUM",
    INSTITUTIONNEL = "INSTITUTIONNEL",
  }

  export enum PlanStatus {
    PROPOSED = "PROPOSED",
    ACCEPTED = "ACCEPTED",
    REJECTED = "REJECTED",
    BROKEN = "BROKEN",
    COMPLETED = "COMPLETED",
  }

  export enum InsuranceStatus {
    ACTIVE = "ACTIVE",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED",
  }

  export enum InsuranceClaimStatus {
    OPEN = "OPEN",
    PROCESSING = "PROCESSING",
    RESOLVED = "RESOLVED",
    REJECTED = "REJECTED",
  }

  export enum MediationStatus {
    OPEN = "OPEN",
    IN_PROGRESS = "IN_PROGRESS",
    RESOLVED = "RESOLVED",
    CLOSED = "CLOSED",
    CANCELLED = "CANCELLED",
  }

  export enum DisputeStatus {
    OPEN = "OPEN",
    WAITING_RESPONSE = "WAITING_RESPONSE",
    IN_MEDIATION = "IN_MEDIATION",
    RESOLVED = "RESOLVED",
    ESCALATED = "ESCALATED",
    CLOSED = "CLOSED",
  }

  export enum PrepaymentRequestStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
  }

  export enum FiscalStatus {
    EN_ATTENTE_DECLARATION = "EN_ATTENTE_DECLARATION",
    NOTIFIE = "NOTIFIE",
    EN_COURS_PAIEMENT = "EN_COURS_PAIEMENT",
    PAYE_CONFIRME = "PAYE_CONFIRME",
    ENREGISTRE = "ENREGISTRE",
    ECHEC_PAIEMENT = "ECHEC_PAIEMENT",
    PAIEMENT_PARTIEL = "PAIEMENT_PARTIEL",
    DECLARATION_EN_RETARD = "DECLARATION_EN_RETARD",
    IGNORE_PAR_BAILLEUR = "IGNORE_PAR_BAILLEUR",
    RENOUVELE = "RENOUVELE",
  }

  export enum MandateType {
    EXCLUSIVE = "EXCLUSIVE",
    SIMPLE = "SIMPLE",
    CO_EXCLUSIVE = "CO_EXCLUSIVE",
    DIRECT = "DIRECT",
  }

  export enum MandateStatus {
    ACTIVE = "ACTIVE",
    SUSPENDED = "SUSPENDED",
    CANCELLED = "CANCELLED",
    EXPIRED = "EXPIRED",
    DRAFT = "DRAFT",
  }

  export enum DeclencheurEnum {
    SOLDE_BAS = "SOLDE_BAS",
    FIN_DE_MOIS = "FIN_DE_MOIS",
    CREDIT_GENERE = "CREDIT_GENERE",
    RAPPEL_MENSUEL = "RAPPEL_MENSUEL",
    MANUEL = "MANUEL",
  }

  export enum ManagementMode {
    AGENCY = "AGENCY",
    DIRECT = "DIRECT",
    MIXED = "MIXED",
  }

  export enum ColocRole {
    PRINCIPAL = "PRINCIPAL",
    SECONDAIRE = "SECONDAIRE",
  }

  export enum ColocMode {
    GROUPE = "GROUPE",
    INDIVIDUEL = "INDIVIDUEL",
    LIBRE = "LIBRE",
  }

  export enum LoyerStatut {
    EN_ATTENTE = "EN_ATTENTE",
    PARTIEL = "PARTIEL",
    COMPLET = "COMPLET",
    EXCEDENT = "EXCEDENT",
    IMPAYE = "IMPAYE",
  }

  export enum TerrainUsage {
    PARKING_VEHICULES = "PARKING_VEHICULES",
    PARKING_CAMIONS = "PARKING_CAMIONS",
    COMMERCE_TEMPORAIRE = "COMMERCE_TEMPORAIRE",
    STOCKAGE = "STOCKAGE",
    AGRICULTURE = "AGRICULTURE",
    EVENEMENTIEL = "EVENEMENTIEL",
    INDUSTRIEL = "INDUSTRIEL",
    AUTRE = "AUTRE",
  }

  export enum Periodicite {
    JOURNALIER = "JOURNALIER",
    HEBDOMADAIRE = "HEBDOMADAIRE",
    MENSUEL = "MENSUEL",
    TRIMESTRIEL = "TRIMESTRIEL",
    SEMESTRIEL = "SEMESTRIEL",
    ANNUEL = "ANNUEL",
    FORFAIT = "FORFAIT",
  }

  export enum VisibEnum {
    INVISIBLE = "INVISIBLE",
    INVITATION_PROPRIO = "INVITATION_PROPRIO",
    INVITATION_AGENCE = "INVITATION_AGENCE",
    TOUS = "TOUS",
  }

  export enum InvitStatutEnum {
    ENVOYEE = "ENVOYEE",
    VUE = "VUE",
    ACCEPTEE = "ACCEPTEE",
    REFUSEE = "REFUSEE",
    EXPIREE = "EXPIREE",
    ANNULEE = "ANNULEE",
  }

  export enum UtilityMode {
    INDIVIDUEL_LOCATAIRE = "INDIVIDUEL_LOCATAIRE",
    PARTAGÉ_PROPRIO = "PARTAGÉ_PROPRIO",
    INDIVIDUEL_PROPRIO = "INDIVIDUEL_PROPRIO",
    MIXTE = "MIXTE",
    NON_APPLICABLE = "NON_APPLICABLE",
  }

  export enum RepartitionModel {
    PRORATA_CHAMBRE = "PRORATA_CHAMBRE",
    FORFAIT_FIXE = "FORFAIT_FIXE",
    USAGE_DÉCLARÉ = "USAGE_DÉCLARÉ",
  }

  export enum UtilityType {
    CIE = "CIE",
    SODECI = "SODECI",
  }

  export enum UtilityStatus {
    EN_COURS = "EN_COURS",
    PAYÉE = "PAYÉE",
    EN_RETARD = "EN_RETARD",
    PARTIELLE = "PARTIELLE",
    EN_ATTENTE = "EN_ATTENTE",
  }

  export enum MaintenanceCategory {
    MAI_EL = "MAI_EL",
    MAI_EA = "MAI_EA",
    MAI_TO = "MAI_TO",
    MAI_SE = "MAI_SE",
    MAI_SA = "MAI_SA",
    MAI_PC = "MAI_PC",
    MAI_AU = "MAI_AU",
    MAI_DI = "MAI_DI",
  }

  export enum MaintenanceStatus {
    EN_ATTENTE = "EN_ATTENTE",
    PRIS_EN_CHARGE = "PRIS_EN_CHARGE",
    RÉSOLU = "RÉSOLU",
    CONTESTÉ = "CONTESTÉ",
    LITIGE = "LITIGE",
    CLÔTURÉ = "CLÔTURÉ",
  }

  export enum ReversalStatus {
    PENDING = "PENDING",
    REVERSED = "REVERSED",
    FAILED = "FAILED",
  }

  export enum ReversalType {
    AGENCY_COMMISSION = "AGENCY_COMMISSION",
    LANDLORD_RENT = "LANDLORD_RENT",
  }

  export enum PaymentCanal {
    ORANGE = "ORANGE",
    MTN = "MTN",
    WAVE = "WAVE",
    MOOV = "MOOV",
    CINETPAY_M17 = "CINETPAY_M17",
    SMS_DECLARATIF = "SMS_DECLARATIF",
  }

  export enum PaymentPgwStatus {
    INITIEE = "INITIEE",
    EN_ATTENTE_PAIEMENT = "EN_ATTENTE_PAIEMENT",
    CONFIRMEE = "CONFIRMEE",
    ECHEC = "ECHEC",
    EXPIREE = "EXPIREE",
    DECLAREE = "DECLAREE",
  }

  export enum EdlType {
    ENTREE = "ENTREE",
    SORTIE = "SORTIE",
  }

  export enum SigDoc {
    BAIL = "BAIL",
    BAIL_COMMERCIAL = "BAIL_COMMERCIAL",
    MANDAT = "MANDAT",
    EDL = "EDL",
    ACCORD_MEDIATION = "ACCORD_MEDIATION",
    AVENANT = "AVENANT",
  }

  export enum SigStatut {
    EN_ATTENTE = "EN_ATTENTE",
    SIGNE = "SIGNE",
    REFUSE = "REFUSE",
    EXPIRE = "EXPIRE",
  }

  export enum CandStatut {
    SOUMISE = "SOUMISE",
    EN_ETUDE = "EN_ETUDE",
    ACCEPTEE = "ACCEPTEE",
    REFUSEE = "REFUSEE",
    CONVERTIE_LOCATAIRE = "CONVERTIE_LOCATAIRE",
  }

  export enum ChargeType {
    EAU = "EAU",
    ELECTRICITE_COMMUNE = "ELECTRICITE_COMMUNE",
    GARDIENNAGE = "GARDIENNAGE",
    NETTOYAGE = "NETTOYAGE",
    TOM = "TOM",
    AUTRE = "AUTRE",
  }

  export enum AgendaType {
    VISITE = "VISITE",
    EDL_ENTREE = "EDL_ENTREE",
    EDL_SORTIE = "EDL_SORTIE",
    REMISE_CLES = "REMISE_CLES",
    REUNION_PROPRIO = "REUNION_PROPRIO",
    TRAVAUX = "TRAVAUX",
    ECHEANCE_BAIL = "ECHEANCE_BAIL",
    AUTRE = "AUTRE",
  }

  export enum LegalType {
    PRE_NOTICE = "PRE_NOTICE",
    COMMAND_TO_PAY = "COMMAND_TO_PAY",
    TERMINATION_NOTICE = "TERMINATION_NOTICE",
    EVICTION_ORDER = "EVICTION_ORDER",
  }

  export enum MigrationStatus {
    UPLOADE = "UPLOADE",
    EN_ANALYSE = "EN_ANALYSE",
    RAPPORT_GENERE = "RAPPORT_GENERE",
    COMMITE = "COMMITE",
    ERREUR = "ERREUR",
  }

  export enum InspectionType {
    ENTRY = "ENTRY",
    EXIT = "EXIT",
  }

  export enum RoomStatus {
    EXCELLENT = "EXCELLENT",
    GOOD = "GOOD",
    FAIR = "FAIR",
    POOR = "POOR",
  }

  export enum ReminderType {
    D_MINUS_5 = "D_MINUS_5",
    D_DAY = "D_DAY",
    D_PLUS_5 = "D_PLUS_5",
    LEGAL_NOTICE = "LEGAL_NOTICE",
  }

  export enum BdqStatut {
    PENDING_LOCATAIRE = "PENDING_LOCATAIRE",
    CONFIRME = "CONFIRME",
    CONFIRME_AGENT = "CONFIRME_AGENT",
    CONFIRME_MEDIATION = "CONFIRME_MEDIATION",
    DECLARATIF_SANS_REPONSE = "DECLARATIF_SANS_REPONSE",
    DECLARATIF_UNILATERAL = "DECLARATIF_UNILATERAL",
    CONTESTE = "CONTESTE",
    FORMALISE = "FORMALISE",
    ARCHIVE = "ARCHIVE",
  }

  export enum BdqConvStatut {
    EN_COURS = "EN_COURS",
    EN_PAUSE = "EN_PAUSE",
    COMPLETE = "COMPLETE",
    ABANDONNE = "ABANDONNE",
    EXPIRE = "EXPIRE",
  }

  export enum NotifCanal {
    WHATSAPP = "WHATSAPP",
    SMS = "SMS",
    EMAIL = "EMAIL",
    PUSH = "PUSH",
  }

  export enum NotifStatut {
    EN_ATTENTE = "EN_ATTENTE",
    ENVOYE = "ENVOYE",
    LIVRE = "LIVRE",
    LU = "LU",
    ECHEC = "ECHEC",
    ANNULE = "ANNULE",
  }

  export enum BienRole {
    OWNER = "OWNER",
    INTERMEDIAIRE = "INTERMEDIAIRE",
    AGENCE = "AGENCE",
    FIELD_AGENT = "FIELD_AGENT",
  }

  export enum ProfilInterm {
    PARENT_AMI = "PARENT_AMI",
    NOTAIRE = "NOTAIRE",
    HUISSIER = "HUISSIER",
    AVOCAT = "AVOCAT",
  }

  export enum RegStatut {
    EN_COURS = "EN_COURS",
    PROLONGE_RECEPISSE = "PROLONGE_RECEPISSE",
    PROLONGE_FORMATION = "PROLONGE_FORMATION",
    REGULARISE = "REGULARISE",
    BASCULE = "BASCULE",
  }

  export enum DeclStatut {
    EN_ATTENTE = "EN_ATTENTE",
    CONFIRME = "CONFIRME",
    CONTESTE = "CONTESTE",
    EXPIRE = "EXPIRE",
    AUTO_GENERE = "AUTO_GENERE",
  }

  export enum PromoType {
    MOIS_GRATUITS = "MOIS_GRATUITS",
    REMISE_POURCENTAGE = "REMISE_POURCENTAGE",
    REMISE_MONTANT = "REMISE_MONTANT",
    PRIX_FIXE = "PRIX_FIXE",
    ESSAI_ETENDU = "ESSAI_ETENDU",
  }

  export enum NegocieType {
    ABONNEMENT_DEROGATOIRE = "ABONNEMENT_DEROGATOIRE",
    QUITTANCE_DEROGATOIRE = "QUITTANCE_DEROGATOIRE",
    ENREGISTREMENT_DEROGATOIRE = "ENREGISTREMENT_DEROGATOIRE",
  }

  export enum SignalCatEnum {
    FUITE_EAU = "FUITE_EAU",
    ELECTRICITE = "ELECTRICITE",
    PORTE_SERRURE = "PORTE_SERRURE",
    NUISANCE = "NUISANCE",
    DEGRADATION = "DEGRADATION",
    AUTRE = "AUTRE",
  }

  export enum SignalStatutEnum {
    ENVOYE = "ENVOYE",
    VU_PROPRIO = "VU_PROPRIO",
    EN_COURS = "EN_COURS",
    RESOLU = "RESOLU",
    NON_RESOLU_FERME = "NON_RESOLU_FERME",
  }

  export enum CautionDestEnum {
    PROPRIETAIRE = "PROPRIETAIRE",
    CDC_CI = "CDC_CI",
    AUTRE = "AUTRE",
  }

  export enum PreavisStatutEnum {
    EMIS = "EMIS",
    ACCUSE = "ACCUSE",
    ETAT_LIEUX_PLANIFIE = "ETAT_LIEUX_PLANIFIE",
    CLOS = "CLOS",
  }

  export enum EdlStatut {
    EN_COURS = "EN_COURS",
    SOUMIS_LOCATAIRE = "SOUMIS_LOCATAIRE",
    CONFIRME = "CONFIRME",
    CONTESTE = "CONTESTE",
    CERTIFIE = "CERTIFIE",
  }

  export enum ProspectStatut {
    A_RAPPELER = "A_RAPPELER",
    EN_DISCUSSION = "EN_DISCUSSION",
    INSCRIT = "INSCRIT",
    PAS_INTERESSE = "PAS_INTERESSE",
    PERDU = "PERDU",
  }

  export enum CommType {
    BAIL_FORMEL = "BAIL_FORMEL",
    BDQ_CONFIRME = "BDQ_CONFIRME",
    FORMALISATION = "FORMALISATION",
    RECRUTEMENT = "RECRUTEMENT",
    BONUS = "BONUS",
  }

}
